{% set name = "pyzxing" %}
{% set version = "1.0.2b" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/ChenjieXu/pyzxing
  git_rev: v{{ version }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - joblib
    - numpy
    - python >=3.6
    - setuptools

test:
  imports:
    - pyzxing
    - src
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ChenjieXu/pyzxing
  summary: Python wrapper for ZXing Java library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ChenjieXu
