language: java
os: linux
dist: bionic
addons:
  apt:
    packages:
      - python3
      - python3-pip
jobs:
  include:
    - jdk: openjdk8
      env:
        - JACOCO=-Pjacoco
install:
  - sudo pip3 install -r requirements.txt
  - sudo python3 setup.py install
script:
  - sudo python3 -m unittest discover
